export {NgxTblModule} from './ngx-tbl.module'
export {NgxTblComponent} from './ngx-tbl-component'
export {NgxTblControl} from './ngx-tbl-control'
export {NgxTblColumn} from './ngx-tbl-column.component'
export {NgxTblPagination} from './ngx-tbl-pagination/ngx-tbl-pagination'